### ISSUE TITLE
Zoom level in edit mode too high

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/leaflet_widget#1]
When I edit a content item with a geofield using Leaflet.widget and with the `Automatically center map` setting enabled, in the map preview I don't see any map details but only a gray area. It seems the zoom level is set to the Maximum of 21 instead to the Default zoom level of 10. As far as I know, 21 is too high for the map in use (OSM Mapnik). Zooming out to level 18 makes the map details visible.

Steps to reproduce:

- Add a Geofield to your content type.
- In the Default map settings:
  - Make sure `Automatically center map on existing features` is enabled.
  - Don't change the zoom levels (Default: 10, Minimum: 0, Maximum: 21).
- Optional: set the Default map center to a reasonable default (e.g. Latitude 51.4777, Longitude -0.0015).
- *Add* a content item. Have a look at the map in the form (it uses the default zoom level), place a marker on the map, and save the item.
- *Edit* the new content item. Have a look at the map again. It uses the maximum zoom level, resulting in a gray area. Zoom out several times to see the map details instead of the gray area.

Workaround: Change the Maximum zoom level in the Default map settings of the field configuration from 21 to 18.

**Comment by indigoxela** [comment]
> Workaround: Change the Maximum zoom level 

That's not the workaround, but the proper solution. Different map types have different max zoom levels. If it's too high, set a lower one.

**Comment by indigoxela** [comment]
Here's a screenshot of that setting, help text highlighted:

![screenshot-map-setting](https://user-images.githubusercontent.com/842066/116196530-eb6ea600-a733-11eb-8a91-2f43f1980986.png)

**Comment by olafgrabienski** [comment]
Thanks for your feedback! I guess I don't agree, though: The defaults should just work, but they don't.

Even if people are generally okay having to change the defaults:

- It isn't clear that the `Automatically center map on existing features` option changes the zoom level.
- There is no option to change the map type in the widget.
- There is no information which zoom level to choose, so that the default map gets visible while editing. You have to find that out by trial and error.

That's not user friendly at all, so expecting people to change the Maximum zoom level isn't a "solution", in my opinion.

What do you think about setting the default maximum zoom level to 18?

**Comment by indigoxela** [comment]
> There is no option to change the map type in the widget.

Enable "Leaflet More Maps", then you get more options.

**Comment by olafgrabienski** [comment]
> Enable "Leaflet More Maps", then you get more options.

Well, and if I don't want to use more maps? Also, that alone doesn't fix the issue.

Isn't a default maximum zoom level of 18 a good solution?

**Comment by indigoxela** [comment]
Should be fixed in 44ecc9b4.

Note: this still doesn't prevent people from setting too high values.

**Comment by olafgrabienski** [comment]
Perfect, the fix works for me. Many thanks!

**Comment by indigoxela** [comment]
Ooops, this is already fixed :smile: , many thanks for reporting and testing.
