### ISSUE TITLE
Default map center: Provide reasonable default(s)

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/leaflet_widget#2]
IIRC, the Default map center of the widget is set to Latitude: 0 / Longitude: 0. The position of this 'neutral' value is ["Null Island", somewhere in the Atlantic Ocean](https://en.wikipedia.org/wiki/Null_Island). Using this point as map center and a medium default zoom level, you just see a blue area:

![backdrop-screen-leaflet-widget-default](https://user-images.githubusercontent.com/14188307/118819913-1624c800-b8b6-11eb-89a9-a8de4cd4f63e.png)

It is a map, but I'm not sure if everyone recognizes it as such. However, to see any map details, you have  and zoom out several times.

I'd suggest to provide a more reasonable default map center. While there doesn't exist a perfect default, the default location used by the Leaflet example map (Latitude 51.4777, Longitude -0.0015) is a reasonable one. It points to London ([Greenwich](https://en.wikipedia.org/wiki/Greenwich)) which is well known for various reasons.

To improve the setting even more, some help text would be nice, e.g.:

> Default: London Greenwich (Latitude: 51.4777, Longitude: -0.0015)
> Other examples: New York City (40.7306, -73.9352), Rio de Janeiro (-22.9083, -43.1964), Tokyo (35.6528, 139.8395)

PS: The examples should be verified, but I'm not sure which service to use.

**Comment by indigoxela** [comment]
This values (0/0) originate from the Drupal version (https://git.drupalcode.org/project/leaflet_widget/-/blob/7.x-2.x/leaflet_widget.module#L24)

I didn't change it because I wasn't sure, which value to choose. Whatever it would be, it's wrong for someone else. :smile:

But more feedback would be nice. Maybe we find (sort of) consensus or a good compromise.

**Comment by indigoxela** [comment]
> The examples should be verified, but I'm not sure which service to use.

Why not using a Leaflet map? :smirk:

**Comment by olafgrabienski** [comment]
> I wasn't sure, which value to choose. Whatever it would be, it's wrong for someone else.

Yes, indeed! I hope however a well known place with visible map details can already be considered better than the current default. In my opinion, London (Greenwich) is a nice location because of its relation via Greenwich Mean Time to the UTC±0 time zone. But sure, it doesn't have to be a place in Europe. Only, I don't know which other one to suggest. Do you have some ideas?

**Comment by indigoxela** [comment]
Finding consensus is always difficult. The _latest dev_ version can automatically center based on GeoIP, if module geoip_tokens is installed. That's configurable in the field default center settings (a checkbox).

**Comment by indigoxela** [comment]
The latest (stable) release now ships with support for the GeoIP Tokens module.

However, I'd like to keep this issue still open for a while, in case someone want's to contribute to the discussion regarding default center (without GeoIP).

![default-center](https://user-images.githubusercontent.com/842066/118833892-1c20a600-b8c2-11eb-9eb7-b8fc55ecc9b1.png)

**Comment by djzwerg** [comment]
Very nice! Great work! Btw it is possible to set the default center at https://[yourdomain]/admin/structure/types/manage/[nodetype]/fields/[yourfield] @olafgrabienski

**Comment by olafgrabienski** [comment]
@djzwerg Thanks for the hint! I know the setting, and sure, once you're aware of it, it's possible to provide a reasonable value. That's fine!

My suggestion has primarily people in mind who are to new to working with maps on the web: The setting might be overseen by them, and in this case, when adding content using the widget, you see nothing than a blue area. (I've added a respective screenshot to the [issue description](https://github.com/backdrop-contrib/leaflet_widget/issues/2#issue-868225688).) Some might even think something isn't working.

**Comment by olafgrabienski** [comment]
Hm, I have another idea for discussion, not sure if it's feasible and if it'd be too much work: is Backdrop aware of the site's top level domain (TLD)? If that's the case, the default map center for sites with a country code in the TLD could be centered around the capital of the respective country (or around the geographical center of the country). Sites without country code (.com, .net etc.) could remain as is, or default to London Greenwich as suggested in the issue description.

**Comment by indigoxela** [comment]
Wow, now it's getting fancy... :laughing: Keep on brainstorming and let's see, where this leads us to.

**Comment by indigoxela** [comment]
It's been a while... :wink:

There will never be a value that fits all, and changing a default is tricky, anyway.
But what we might have available is the default country setting (from admin/config/regional/settings). And we could add a small widget, that geocodes from that setting (sets the coords to the center of the default country).

@olafgrabienski what do you think?

![default-map-center-geocode-widget](https://github.com/user-attachments/assets/f96897dd-4425-42d9-a02b-fd8224faf945)

"Austria" is obviously the testing site's default country setting. :wink:

**Comment by olafgrabienski** [comment]
> But what we might have available is the default country setting (from admin/config/regional/settings). And we could add a small widget, that geocodes from that setting (sets the coords to the center of the default country).

This is a very good idea, in my opinion!

**Comment by indigoxela** [comment]
> This is a very good idea, in my opinion!

Cool! :smile: 

How about testing my PR? Not sure, when you find the time, but here's a patch to apply (if you want to use a patch): https://patch-diff.githubusercontent.com/raw/backdrop-contrib/leaflet_widget/pull/22.diff

**Comment by olafgrabienski** [comment]
Sure, I've applied the changes on a test site. Setting the default values to the country center (Germany, in my case) works like a charm, and when I create a new content item, the new default value is respected.

Node form after setting to the center of Germany:
<img src="https://github.com/user-attachments/assets/4dde3028-4b70-4b8c-9ef6-06df8bec642f" width="450">
