### ISSUE TITLE
Simplification for just one marker?

### ISSUE THREAD

**Issue by AlexHoebart-ICPDR** [backdrop-contrib/leaflet_widget#23]
Hi,
this is indeed a very nice module, thank you. I am converting an application from D7 using getlocations module and this module works very well as replacement (with some data transformations). I have it working in principle. 

The only issue I have is that usage is now more complicated with my simple use case: users enter a location name in the search box and select one option found to be marked on the map. Then they should be able to move the marker to correct the exact position. This should be possible by simply dragging the marker.

With the current widget, users have to click on the edit icon, then drag, then click on save. 
Same with add one marker without searching: They have to click on the marker icon and only then they can set it.

Is it possible to simplify the widget for such simple use case - to just click to create and drag to move?
I see an existing example where there is a marker which can be dragged, but I could not find out how to achieve this:
https://leaflet.github.io/Leaflet.draw/docs/examples/snapping.html

I would only need one marker, no other geometry types and no delete option. I would appreciate any hint to get me in the right direction.

**Comment by indigoxela** [comment]
> With the current widget, users have to click on the edit icon, then drag, then click on save.

That's how Leaflet.draw (the library) works, yes.

> Is it possible to simplify the widget for such simple use case...

No, it would require to write a new library. Or at least, override large parts of it with a custom class.
