### ISSUE TITLE
Only NDR (little endian) SKB format is supported at the moment

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/leaflet_widget#3]
See https://www.drupal.org/project/leaflet_widget/issues/2456915.

**Comment by indigoxela** [comment]
Caution: the "port" uses a *completely different js library* than the Drupal project.

And the Drupal project is known to be completely broken.

**Comment by djzwerg** [comment]
Please have a look at the small code changes. I think there is no dependency of the library in that case.

**Comment by indigoxela** [comment]
Additionally, this widget depends on a completely different Leaflet library version (recent) compared to the ancient Drupal Leaflet module.

So before you come with patches, you have to proof, that this is really applicable to THIS module, which is a complete rewrite of the Drupal one.

**Comment by indigoxela** [comment]
Read my comments, please. :wink:

**Comment by djzwerg** [comment]
I have tested it on my own and the error messages have been gone 😉

**Comment by indigoxela** [comment]
I need steps to reproduce. Only a link as a bug report is *not* enough.

**Comment by djzwerg** [comment]
Sorry, my fault.

Steps to reproduce:

1. Create nodes with a Geofield (without the widget)
2. Install leaflet_widget
3. Try to edit your created nodes
4. Have a look at the error log

**Comment by indigoxela** [comment]
> Create nodes with a Geofield (without the widget)

How did you create them? With coordinates or via some geocoding? If the latter - which modules (module combination) did you use? Was that on D7 or on B?

**Comment by djzwerg** [comment]
I'd create them with the widget `WKT`:
`POINT (lat long)`

This issue occured on an upgraded D7 to B site after the upgrade but I was able to reproduce it on a fresh B install, too.

**Comment by indigoxela** [comment]
> I'd create them with the widget WKT:

Which module ships with that widget?

**Comment by djzwerg** [comment]
Geofield only

**Comment by indigoxela** [comment]
Hm, something else must interfere on your site, I'm not able to reproduce.

This is what I did:

- Switched the widget to WKT (geofield)
- Created a new node (with geofield), input WKT `POINT(-122.34009 47.60995)` and saved the node
- Nice, map shows
- Switched the widget back to Leaflet.widget
- Opened that node again, nice, marker shows and is editable
- Nothing in console log
- Edited and saved
- No error, map shows (debug($form_state['process_input']) is NULL), so that if doesn't strike)

Whatever causes the problem on your site - it's not that if clause.

**Comment by indigoxela** [comment]
Can you provide some of your problematic input (WKT)?
Are you sure, there's no geocoding module active on your site?

**Comment by djzwerg** [comment]
It looks like this occurs in combination with geo_php module: https://www.drupal.org/project/geophp/issues/2446023 (I'm using this, too.)

**Comment by indigoxela** [comment]
Can you describe the steps, please? How are you using Leaflet.widget in combination with geo_php? :confused: Or, most of all... WHY?

**Comment by djzwerg** [comment]
I believe this was a remnant of the old version with OpenLayers and thought it was a requirement for Leaflet.

**Comment by indigoxela** [comment]
> I believe this was a remnant of the old version with OpenLayers and thought it was a requirement for Leaflet.

No dependency, the Leaflet module works standalone. And the widget (this module) only needs Leaflet (and a geofield, of course).

**Comment by indigoxela** [comment]
What's still unclear, and this time please really answer my questions :wink: :

- Which mapping- and geolocation related modules are enabled on your site?
- How is your geofield configured?

**Comment by djzwerg** [comment]
I've tested it again and can confirm that this issue only occurs if you have geo_php enabled. I've checked my mapping- and geolocation modules and for now I'm using **geofield, leaflet and leaflet_widget**.

My geofield is using leaflet_widget as widget-type and OSM Mapnik to set the locations.

The issue has been gone since I've uninstalled geo_php.

**Comment by indigoxela** [comment]
> The issue has been gone since I've uninstalled geo_php.

A little strange, though, that the module interferes when it's only installed, but nothing requires it and it's also not configured to handle anything... :thinking:

**Comment by djzwerg** [comment]
Yes that confuses me, too...

**Comment by djzwerg** [comment]
After clearing all caches the issues occurs again:

`Exception: Only NDR (little endian) SKB format is supported at the moment in WKB->getGeometry() (line 52 of /mypath/modules/geofield/libraries/geophp/lib/adapters/WKB.class.php).`

location:
`https://domain/file/ajax/field_image/und/form-112r7vbnY1XCj49--tzpN7xgXXmSsKycha0Bt-PaET4/g8r0_N9lF3k9Cf68iU7fFLatwWo1nfXS9t1GIyNnyTI`

Maybe it occurs only if you have ajax enabled on node creation (e.g. using resumable uploads).

Maybe this is an issue of geofield_module? But the PR solves this.

**Comment by indigoxela** [comment]
Although I still can't reproduce the problem, I'll merge your PR. I read through the whole Drupal issue and compared code (geophp, geofield). This code actually seems outdated, anyway.

If this breaks something, I'm sure somebody will report.
